// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACBCAJxMklXBmp4v2wgM5MueQBHg0mqec',
    appId: '1:941759805310:web:cf1de991bef990141a652f',
    messagingSenderId: '941759805310',
    projectId: 'vinta-finacas',
    authDomain: 'vinta-finacas.firebaseapp.com',
    storageBucket: 'vinta-finacas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWaFO9VD8PvMbwf3IO6UjZXQNKeGCKK8s',
    appId: '1:941759805310:android:12787192b214c6951a652f',
    messagingSenderId: '941759805310',
    projectId: 'vinta-finacas',
    storageBucket: 'vinta-finacas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYHqWMpbRzfYpMLSrSQBZhtUajG0LlJwo',
    appId: '1:941759805310:ios:42accf5ec51ab38b1a652f',
    messagingSenderId: '941759805310',
    projectId: 'vinta-finacas',
    storageBucket: 'vinta-finacas.firebasestorage.app',
    iosBundleId: 'com.example.vintaFinancas',
  );
}
